### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by Yeedle** [tidyverse/tidyweb#7]
I think the tidyverse deserves its own dedicated style guide, as the manner of code differs significantly from the non-tidyverse approach. I started compiling [one](http://rpubs.com/yeedle/tidyguide), but perhaps something more "official" would be helpful.

**Comment by Yeedle** [comment]
Can probably be closed in light of [tidyverse/style](https://github.com/tidyverse/style)?

**Comment by hadley** [comment]
Yup, thanks!
